### PR TITLE
Generate last_updated

### LINKED ISSUE #317: Autogenerate timestamps
As part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/302 and https://github.com/HTTPArchive/almanac.httparchive.org/pull/308 we added Article Structured Data which depends on having a Published Date (required or it fails the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool)) and a Last Updated Date (recommended by the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool)). These have been implemented in the chapter markdown files as meta data. For example:

```
---
part_number: IV
chapter_number: 20
title: HTTP/2
description: HTTP/2 chapter of the 2019 Web Almanac covering adoption and impact of HTTP/2, HTTP/2 Push, HTTP/2 Issues, and HTTP/3
authors: [bazzadp]
reviewers: [bagder, rmarx, dotjs]
published: 2019-11-04T12:00:00+00:00:00
last_updated: 2019-11-04T12:00:00+00:00:00 
---
```

This allows for different timestamps for different publication dates and also for different timestamps for the translations which might be published at different dates - hence why I put it in the markdown.

At present these dates must be manually maintained which @rviscomi and I have been discussing.

I think that makes sense for the Published Date as this should be set once and forgotten about, but for the last_updated this is more error prone and people may forget to update them when changing the contents.

It should **not** be generated as part `npm run generate` as the contents my not have changed for every chapter (or even any chapter!) when it is run, and also generic formatting changes, which are not specific to this chapter (e.g. when base_chapter.html or chapter.html is updated) probably don't count as a "real edit".

Requirements:
- Auto update `last_updated` meta data in chapter md files when a merge is accepted into that chapter’s markdown. Is it possible to do this as part of a GitHub action?

The format currently has to be as per above example, however this will be converted as part of `npm run generate` as per https://github.com/HTTPArchive/almanac.httparchive.org/pull/345 so less of a concern (and we should use an easier format for authors!).
- ~~Bonus points 1 - have a global "earliest publish date" per year and auto flag any date (`published` or `last_updated`) before then (or when a date is not present?) to prevent errors creeping in and prevent the merge. Set this global constant to 2019-11-04T12:00:00+00:00:00 for now and then we can update it later once we have an actual publish date.~~ This has been implemented as part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/345
- Bonus points 2 - also do the non-chapter pages (Home, methodology, ToC, Contributors) though these may be trickier as just embedded in HTML at present.

@mikegeyser any thoughts on this?

### PR DESCRIPTION
**Pull request by mikegeyser**
This closes #317.

This PR adds a generate script for the `last_updated` timestamp on every content file. It is not tightly coupled to the `generate_chapters` functionality, because we might want it to be a pre-commit hook instead. At the moment it will run first and uses the date of the latest commit on the file to generate the `last_modified`.

I'm a little nervous of the updating of source files, but I do think it's better than having to do it by hand.

### CODE REVIEW

File: src/tools/generate/generate_last_updated.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  }
+};
+
+const get_last_updated_date = (path) => {
+  const command = `git log -1 --date=iso-strict-local ${path} | cat`;
+  const stdout = execSync(command).toString();
+  const date_string = /Date:\s+(\S*)/g.exec(stdout)[1];
+  const date = new Date(date_string);
+
+  return date.toISOString();
```
Comment (mikegeyser) [inline src/tools/generate/generate_last_updated.js]: This uses the ISO_8601 format of representing UTC timezone with a `Z`, instead of `+00:00`. I can change this if needed.

Comment (bazzadp) [reply src/tools/generate/generate_last_updated.js]: As per https://github.com/HTTPArchive/almanac.httparchive.org/issues/317#issuecomment-551154505 think that is fine.
